const now = new Date();

export const demoUserData: { user: userType; contacts: contactType[]; events: eventsType[] } = {
  user: {
    id: 'demoUser',
    email: 'demo.user@email.com',
    displayname: 'Demó Felhasználó',
    settings: {
      saveMode: 'auto',
    },
  },
  contacts: [
    {
      id: 'democontact1',
      name: 'Fodrász',
      comment: '',
    },
    {
      id: 'democontact2',
      name: 'Iroda',
      color: '#dd2e88',
    },
    {
      id: 'democontact3',
      name: 'Vidéki Rendezvények',
      color: '#7add2d',
    },
    {
      id: 'democontact4',
      name: 'Edzés',
      color: '#2ddda3',
    },
    {
      id: 'democontact5',
      name: 'Ünnepnapok',
      color: '#c2bf23',
    },
    {
      id: 'democontact6',
      name: 'Rendkívüli Események',
      color: '#fd4f4f',
    },
  ],
  events: [
    {
      id: 'demoevent11',
      type: 'single',
      title: 'Fodrász',
      start: new Date(now.getFullYear(), now.getMonth(), 1, 14, 0),
      end: new Date(now.getFullYear(), now.getMonth(), 1, 14, 30),
      comment: 'Szabó Hajni - 30 000 Ft előre',
      contactId: 'democontact1',
    },
    {
      id: 'demoevent12',
      type: 'single',
      title: 'Hajfestés',
      start: new Date(now.getFullYear(), now.getMonth(), 15, 14, 0),
      end: new Date(now.getFullYear(), now.getMonth(), 15, 16, 0),
      contactId: 'democontact1',
    },
    {
      id: 'demoevent21',
      type: 'single',
      title: 'Videó konferencia',
      start: new Date(now.getFullYear(), now.getMonth(), 6, 10, 0),
      end: new Date(now.getFullYear(), now.getMonth(), 6, 12, 30),
      comment: 'Bertalan János marketing csapat + Athéné Kft.',
      contactId: 'democontact2',
    },
    {
      id: 'demoevent22',
      type: 'single',
      title: 'Fizetés nap',
      start: new Date(now.getFullYear(), now.getMonth(), 10, 0, 0),
      allDay: true,
      contactId: 'democontact2',
    },
    {
      id: 'demoevent23',
      type: 'single',
      title: 'Céges vacsora',
      start: new Date(now.getFullYear(), now.getMonth() + 1, 10, 14, 0),
      end: new Date(now.getFullYear(), now.getMonth() + 1, 10, 16, 0),
      contactId: 'democontact2',
    },
    {
      id: 'demoevent24',
      type: 'single',
      title: 'Excel tábla elküldése',
      start: new Date(now.getFullYear(), now.getMonth(), 24, 0, 0),
      allDay: true,
      contactId: 'democontact2',
    },
    {
      id: 'demoevent31',
      type: 'single',
      title: 'Szeged - oktatás',
      start: new Date(now.getFullYear(), now.getMonth(), 11, 14, 0),
      end: new Date(now.getFullYear(), now.getMonth(), 13, 14, 0),
      contactId: 'democontact3',
    },
    {
      id: 'demoevent32',
      type: 'single',
      title: 'Tata + Tatabánya',
      start: new Date(now.getFullYear(), now.getMonth() + 1, 12, 8, 0),
      end: new Date(now.getFullYear(), now.getMonth() + 1, 13, 18, 0),
      comment: 'bring cash - 168 000 Ft',
      contactId: 'democontact3',
    },
    {
      id: 'demoevent33',
      type: 'single',
      title: 'Vecsés',
      start: new Date(now.getFullYear(), now.getMonth() + 1, 28, 9, 0),
      end: new Date(now.getFullYear(), now.getMonth() + 1, 28, 16, 30),
      contactId: 'democontact3',
    },
    {
      id: 'demoevent41',
      type: 'recurring',
      title: 'Edzés',
      start: new Date(now.getFullYear(), now.getMonth(), 3, 8, 0),
      end: new Date(now.getFullYear(), now.getMonth(), 3, 9, 0),
      recurrenceData: {
        groupId: null,
        rrule: {
          dtstart: new Date(now.getFullYear(), now.getMonth(), 3, 8, 0).toISOString(),
          freq: 'weekly',
          byweekday: [2, 5],
          interval: 1,
        },
      },
      contactId: 'democontact4',
    },
    {
      id: 'demoevent51',
      type: 'recurring',
      title: 'Anna születésnap',
      start: new Date(now.getFullYear(), now.getMonth(), 21, 0, 0),
      allDay: true,
      recurrenceData: {
        groupId: null,
        rrule: {
          dtstart: new Date(now.getFullYear(), now.getMonth(), 21, 0, 0).toISOString(),
          freq: 'monthly',
          interval: 12,
        },
      },
      contactId: 'democontact5',
    },
    {
      id: 'demoevent61',
      type: 'single',
      title: 'Állatorvos',
      start: new Date(now.getFullYear(), now.getMonth(), 25, 12, 0),
      end: new Date(now.getFullYear(), now.getMonth(), 25, 13, 30),
      contactId: 'democontact6',
    },
    {
      id: 'demoevent62',
      type: 'single',
      title: 'Könyv Átvétel',
      start: new Date(now.getFullYear(), now.getMonth(), 10, 10, 0),
      end: new Date(now.getFullYear(), now.getMonth(), 10, 10, 30),
      comment: 'Asztória - Rákóczi út',
      contactId: 'democontact6',
    },
  ],
};
